apiVersion: v1
kind: Secret
metadata:
  name: sausage-backend-report-{{ .Release.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: sausage-backend-report
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/component: backend-report
    app.kubernetes.io/part-of: sausage-store
    env: "{{ .Values.environment }}"
type: Opaque
stringData:
  DATABASE_PASSWORD: "{{ .Values.secrets.dbPassword }}"
  DATABASE_CONNECTION_STRING: "{{ .Values.global.database.connectionString }}"
